/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:05494374-d4ce-403f-91a6-57b726509d79",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_8RhrtoL1s",
    "aws_user_pools_web_client_id": "109qcokpgs15gte3qkshkhqodn",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://7saxk6md7bf57bcm2rpkeuvlxq.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
